<section>
<div class="card card-info">
		<div class="card-header">
		    <h3 class="card-title">Ventas Diarias</h3>
		</div>
		    
		<div class="card-body">
		    <canvas id="pieChart" style="min-height: 250px; height: 400px; max-height: 600px; max-width: 100%;"></canvas>
		</div>
</div>
	
</section>







<?php
include("graf.php"); 
?>
<script src="<?php echo BASE_URL;?>layout/admin/js/Chart.min.js"></script>
<script src="<?php echo BASE_URL;?>layout/admin/plugins/jquery/jquery.min.js"></script>

<script src="https://code.jquery.com/jquery-1.12.4.js"> </script>
		<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"> </script>
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"> </script>
		
<script>
	
	$(function () {
	
    var pieChartCanvas = $('#pieChart').get(0).getContext('2d')
    
    var pieData        = {
      labels: <?php echo json_encode($date); ?>,
      datasets: [{
      data: <?php echo json_encode($datchart);?>,
      backgroundColor :
       ['#f56954', '#00a65a', '#f39c12', '#00c0ef', '#3c8dbc','#54478c',
       '#2c699a','#048ba8','#0db39e','#16db93','#83e377','#b9e769','#efea5a',
       '#f1c453','#f29e4c'],}]}
    
    var pieOptions     = {maintainAspectRatio : false, responsive : true, }
    
    var pieChart = 
    new Chart(pieChartCanvas, {type: 'bar', data: pieData,options: pieOptions})
    
})
</script>