<!DOCTYPE html>
<html>
	<head>
		<title>The Resistance</title>
		<link rel="icon" href="imagenes/diseno.ico">
		<meta charset="utf-8">
		<link rel="stylesheet" href="css/diseño.css">
		<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

	</head>
	<body>
		<div id="container">
			<header>
				<h1><img src="imagenes/disenicono.png" width="60" alt="Diseño" title="Diseño">The Resistance</h1>
			</header>
			<nav id="menu">
				<ul>
					<li>
						<a class="link" href="index.html">Página Principal</a></li>
					<li>
						<a class="link" href="Complementos_Bootstrap.html">Bootstrap</a></li>
					<!--<li><a class="link" href="EjemplosBootstrap.html">Bootstrap</a></li>-->
					<li>
						<a class="link" href="Complementos_Jquery.html">Jquery UI</a></li>
					<li>
						<a class="link" href="sitioenconstruccion.html">Proyecto Final</a></li>
				</ul>
			</nav>
			<div class="clearfix"></div>
			<section id="content">
				<article class="article">
					<h2>¿Qué es HTML?</h2>

					<p>HTML es el lenguaje con el que se define el contenido de las páginas web. Básicamente se trata
						de un conjunto de etiquetas que sirven para definir el texto y otros elementos que compondrán una
						página web, como imágenes, listas, vídeos, etc.</p>
					<p>El HTML se creó en un principio con objetivos divulgativos de información con texto y algunas
						imágenes. No se pensó que llegara a ser utilizado para crear área de ocio y consulta con carácter
						multimedia (lo que es actualmente la web), de modo que, el HTML se creó sin dar respuesta a
						todos los posibles usos que se le iba a dar y a todos los colectivos de gente que lo utilizarían en un
						futuro. Sin embargo, pese a esta deficiente planificación, si que se han ido incorporando
						modificaciones con el tiempo, estos son los estándares del HTML.
					</p>
				</article>
				<article class="article">
					<h2>¿Qué es CSS?</h2>

					<p>CSS (en inglés Cascading Style Sheets) es lo que se denomina lenguaje de hojas de estilo en
						cascada y se usa para estilizar elementos escritos en un lenguaje de marcado como HTML. CSS
						separa el contenido de la representación visual del sitio.</p>
					<h4>¿Qué es Cascada?</h4>
					<p>Además de la herencia, otro de los conceptos más importantes de CSS es el concepto de cascada.
						Este concepto es un poco más avanzado, por lo que se debe conocer bien el tema de selectores CSS y dominar algo de CSS para comprenderlo en su totalidad, por lo que si no es el caso se puede posponer para una lectura posterior. En un primer nivel de simplicidad, la cascada en las hojas de estilo significa que el orden de las reglas importa en CSS: cuando dos reglas tienen la misma especificidad, se aplica la que viene en último lugar en el CSS.</p>
					<h4>Características del CSS</h4>
					<ol>
						<li>Complementariedad con documentos estructurados.</li>
						<li>Mantenibilidad.</li>
						<li>Simplicidad.</li>
						<li>Rendimiento de la red.</li>
						<li>Flexibilidad.</li>
						<li>Combinación con lenguajes alternativos.</li>
						<li>Accesibilidad.</li>
					</ol>
				</article>
				<article class="article">
					<h2>Modelos de caja</h2>

					<p>Los navegadores consideran cada elemento HTML de una página web como un grupo de cajas ordenadas
						siguiendo ciertas reglas. Estas reglas son establecidas por estilos provistos por los navegadores o por los diseñadores usando CSS.</p>
					<p>CSS tiene un set predeterminado de propiedades destinados a sobrescribir los estilos provistos por
						navegadores y obtener la organización deseada. Estas propiedades no son específicas, tienen que ser
						combinadas para formar reglas que luego serán usadas para agrupar cajas y obtener la correcta disposición
						en pantalla. La combinación de estas reglas es normalmente llamada modelo o sistema de disposición.
						Todas estas reglas aplicadas juntas constituyen lo que se llama un modelo de caja. El término "modelo de
						caja" se usa cuando se habla de diseño y maquetación. El modelo de caja en CSS es esencialmente una caja
						que envuelve cada elemento HTML.</p>
				</article>
			</section>

			<aside id="sidebar">
				<h2>Caracteristicas de HTML</h2>
				<form>
					<input type="text">
					<!--<input type="submit" value="Buscar">-->
					<button class="btn btn-primary">Buscar</button>
				</form>
				<ul>
					<li>El Web tenía que ser distribuido: La información repartida en páginas no muy grandes enlazadas
						entre sí.</li>
					<li>El Web tenía que ser hipertexto y debía ser fácil navegar por él.</li>
					<li>Tenía que ser compatible con todo tipo de ordenadores y con todo tipo de sistemas operativos.</li>
					<li>Debía ser dinámico: el proceso de cambiar y actualizar la información debía ser ágil y rápido</li>
					<li>Puede ser creado y editado con cualquier editor básico de textos.</li>
					<li>Es multiplataforma, o sea, puede ser visualizado por cualquier navegador de cualquier sistema
						operativo.</li>
					<li>Es utilizado para la creación de páginas web.</li>
					<li>Es un estándar reconocido por todo el mundo y cuyas normas define un organismo sin animo de
						lucro llamado World Wide Web Consortium, más conocido como W3C.</li>
				</ul>
				<p>Por mencionar algunos.</p>
			</aside>
			<div class="clearfix"></div>
			<footer>
				<h3>The Resistance &copy; 2020 | Programación 4</h3>
			</footer>
		</div>

		<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"> </script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"> </script>

	</body>
</html>