<section class="content">
      	<div class="container-fluid">
      		<div class="card card-danger">
	            <div class="card-header">
	            	<h3 class="card-title">Consulta de Solicitudes</h3>
	            </div>
              <!-- /.card-header -->
              	<div class="card-body">
               		<table id="consulta_solicitud" class="display" style="width: 100%">
		                <thead>
		                	<tr>
			                    <th>Id Solicitud</th>
			                    <th>Descripción</th>
			                    <th>Telefono</th>
			                    <th>Dirección</th>
			                    <th>Correo</th>
			                    <th>Puesto</th>
			                    <th>Fotografía</th>
			                    <th>Curriculum</th>
			                    <th>Estado Registro</th>
		                  	</tr>
		                </thead>
                  
                  
                </table>
              </div>
              <!-- /.card-body -->
        	</div>
        	<button type="button" id="consultar" class="btn btn-danger">Consulta</button>
    	</div>
</section>