
<section class="content">
    <div class="card card-warning ">
        <div class="card-header">
          <h1 class="card-title">Mantenimiento de Solicitudes con jqGrid</h1>
        </div>
        <div class="card-body" >
        	<table id="list3"></table>
			<div id="pager3"></div>
			<br>
        </div>
        <!-- /.card-body -->
    </div>
</section>



<!-- Modal subir fotografia-->
<div class="modal fade" id="Mod_foto" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Subir Fotografía</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        
        
        <input id="input-pic" name="input-pic[]" type="file" class="file" data-browse-on-zone-click="true">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-info" data-dismiss="modal">Cerrar</button>
        <button type="button" class="btn btn-success">Cargar Archivo</button>
      </div>
    </div>
  </div>
</div>



<!-- Modal subir curriculum-->
<div class="modal fade" id="Mod_pdf" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Subir Curriculum</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <input id="input-pdf" name="input-pdf" type="file" class="file" multiple 
    data-show-upload="false" data-show-caption="true" data-msg-placeholder="Seleccione archivo para subir...">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-info" data-dismiss="modal">Cerrar</button>
        <button type="button" class="btn btn-success">Cargar Archivo</button>
      </div>
    </div>
  </div>
</div>
