<link rel="stylesheet" type="text/css" href="css/estilo.css"/>
		<link rel="stylesheet" type="text/css" media="screen"
		href="libraries/jqgrid/text/css/ui-lightness/jquery-ui-1.10.1.custom.min.css" />
		
		<link rel="stylesheet" 
		href="https://cdnjs.cloudflare.com/ajax/libs/free-jqgrid/4.14.0/css/ui.jqgrid.min.css"/>

		<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.12.4/jquery.min.js"> </script>
		<!--script que carga el idioma de jqgrid, visible al usuario-->
		<script src="libraries/jqgrid/js/i18n/grid.locale-es.js" type="text/javascript"> </script>
		<!-- Load pdfmake lib files -->
	<script type="text/javascript" language="javascript" 
	src="//cdn.rawgit.com/bpampuch/pdfmake/0.1.26/build/pdfmake.min.js">	</script>
	<script type="text/javascript" language="javascript" 
	src="//cdn.rawgit.com/bpampuch/pdfmake/0.1.26/build/vfs_fonts.js"></script>
	
		<script src="https://cdnjs.cloudflare.com/ajax/libs/free-jqgrid/4.14.0/jquery.jqgrid.min.js"></script>

<section class="content">
      <div class="card card-info ">
        <div class="card-header">
          <h3 class="card-title">MANTENIMIENTO DE FACTURAS</h3>
        </div>
        <!-- /.card-header -->
        <div class="card-body">
        	<table id="mantenimientofa"></table>
			<div id="pagermf"></div>
			<br>
        </div>
        <!-- /.card-body -->
      </div>
      <!-- /.card -->
    </section>


