<section class="content">
      	<div class="container-fluid">
      		<div class="card card-success">
	            <div class="card-header">
	            	<h3 class="card-title">Detalle de facturas</h3>
	            </div>
              <!-- /.card-header -->
              	<div class="card-body">
               		<table id="consulta_detalle" class="display" style="width: 100%">
		                <thead>
		                	<tr>
			                    <th>Id Dt factura</th>
			                    <th>Id Producto</th>
			                    <th>Id Factura</th>
			                    <th>Cantidad</th>
			                    <th>Precio</th>
			                    <th>Pago</th>
		                  	</tr>
		                </thead>
                </table>
              </div>
              <!-- /.card-body -->
        	</div>
        	<button type="button" id="consultar" class="btn btn-info">Ver detalle</button>
    	</div>
</section>