<link rel="stylesheet" href="<?php  echo BASE_URL; ?>layout/admin/css/estilos.css"/>
<div class="container">
	<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
		<div class="carousel-inner">
			<div class="carousel-item active">
				<img src="<?php echo $layout['img']; ?>bootstrap-4.jpg" class="d-block w-100" alt="...">
			</div>
			<div class="carousel-item">
				<img src="<?php echo $layout['img']; ?>bootstrap-social.png" class="d-block w-100" alt="...">
			</div>
			<div class="carousel-item">
				<img src="<?php echo $layout['img']; ?>bstrap1.jpg" class="d-block w-100" alt="...">
			</div>
			<div class="carousel-item">
				<img src="<?php echo $layout['img']; ?>bootstrap-wallpaper.png" class="d-block w-100" alt="...">
			</div>
		</div>

		<a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
			<span class="carousel-control-prev-icon" aria-hidden="true"></span>
			<span class="sr-only">Previous</span>
		</a>
		<a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
			<span class="carousel-control-next-icon" aria-hidden="true"></span>
			<span class="sr-only">Next</span>
		</a>
	</div>

	<div class="clearfix visible-sm-block"></div>
	<br>

	<section class="main row">
		<article class="col-xs-12 col-sm-8 col-md-9 col-lg-9">
			<h2>Bootstrap</h2>
			<p>Bootstrap es una librería CSS, es decir, es un archivo CSS que añades en tus proyectos para tener una serie de estilos ya preparados para utilizar. Inicialmente, se llamó Twitter Blueprint y, un poco más tarde, en 2011, se transformó en código abierto y su nombre cambió para Bootstrap. Desde entonces fue actualizado varias veces y ya se encuentra en la versión 4.4. </p>

			<p>El framework combina CSS y JavaScript para estilizar los elementos de una página HTML.
				Permite mucho más que, simplemente, cambiar el color de los botones y los enlaces.</p>

			<h2>Grid con Sistema de Rejillas</h2>
			<p>Lo que hace Bootstrap es definir un modelo de divisor horizontal (una fila) divisible en 12
				columnas. Pero con la ventaja de que podemos decir cuantas hay en cada resolución de pantalla.
				Esto es muy fácil de entender con un ejemplo simple: pensemos en una serie de bloques (imagenes,
				divisores. lo que sea) que cuando estamos en pantalla LG (más de 1200 pixels) queremos que estén
				todos en fila. Pero que a medida que se vaya estrechando la pantalla, en vez de desaparecer de la
				vista, vayan saltando de línea: 3 por fila en resolución MD (de más de 992 pixels), 2 por fila en
				resoluciones SM (de más de 768px), y uno por fila en móviles (pantalla XS)</p>

			<p>El código con el cual se programa ese sistema de columnas es el siguiente:</p>
			<img src="<?php echo $layout['img']; ?>codigo.jpg">
			<p>Acá podemos ver la forma en que el código se representa en una forma más gráfica:</p>
			<img src="<?php echo $layout['img']; ?>columna.jpg">

		</article>

		<aside class="col-xs-12 col-sm-4 col-md-3 col-lg-3">
			<h2>Ventajas</h2>
			<ul>
				<li>Facilidad de uso. Lo único que tienes que hacer es poner clases a elementos HTML.</li>
				<li>Responsive. Perfecto para crear páginas web adaptables a cualquier dispositivo.</li>
				<li>Personalizable. Puedes personalizar su descarga para usar los elementos que necesites.</li>
				<li>Gran comunidad. Este framework está muy extendido y si tenemos un problema podremos
					encontrar mucha información en Internet.</li>
			</ul>

			<h2>Se compone de dos directorios:</h2>
			<ul>
				<li>Css: contiene los archivos necesarios para la estilización de los elementos y una
					alternativa al tema original;</li>
				<li>Js: contiene la parte posterior del archivo bootstrap.js (original y minificado),
					responsable de la ejecución de aplicaciones de estilo que requieren manipulación
					interactiva.</li>
			</ul>
		</aside>


	</section>


	<div class="row">
		<div class="color1 col-xs-12 col-sm-6 col-md-3">
			<h2>Características del bootstrap</h2>
			<p>Una de las principales características de esta práctica es que supone un remuestreo posterior para poder obtener expresiones cerradas y solucionar la complejidad matemática de estas operaciones. Con el desarrollo de los ordenadores y herramientas tecnológicas en los últimos años, se ha hecho más fácil poder contar con el uso del bootstrapping para remuestreos complejos.</p>
			<p>La técnica del remuestreo permite ir más allá a la hora de estudiar muestras de datos de una determinada población. En otras palabras, permite hacer o crear nuevos supuestos sustituyendo valores adicionales de la muestra.</p>
		</div>
		<div class="clearfix visible-sm-block"></div><!-- clearfix permite limpiar errores de sitio web en el tamaño, el visible-sm determina a partir de que tamaño empieza a ejecutarse -->

		<div class=" card col-xs-12 col-sm-6 col-md-3" style="width: 18rem;">
			<img src="<?php echo $layout['img']; ?>card.png" class="card-img-top" alt="...">
			<div class="card-body">
				<h5 class="card-title"> Ejemplo de Card title</h5>
				<p class="card-text">se puede colocar un contenido en esta parte para que se visualice al cargar la página.</p>
				<a href="Complementos_Bootstrap.html" class="btn btn-primary">Volver Arriba</a>
			</div>
		</div>
		<div class="clearfix visible-sm-block"></div>

		<div class="color1 col-xs-12 col-sm-6 col-md-3">
			<h2>Read only</h2>
			<input class="form-control" type="text" placeholder="Entrada de solo lectura aquí..." readonly>
		</div>
		<div class="clearfix visible-sm-block"></div>

		<div class="col-xs-12 col-sm-6 col-md-3">
			<p>

				<button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
					Botón Colapsable con información
				</button>
			</p>
			<div class="collapse" id="collapseExample">
				<div class="card card-body">
					este botón colapsable, es para mostrar contenido oculto para el visitante, hasta que este de click en el mismo botón, de igual forma para volverlo a ocultar, se debe dar click nuevamente
				</div>
			</div>

		</div>

	</div>

	<script src="https://code.jquery.com/jquery-1.12.4.js"> </script>
	<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"> </script>

	<br>
	<form>
		<button class="btn btn-primary">Volver Arriba</button>
	</form>


	<div class="clearfix"></div>
	<br>
	<nav aria-label="...">
		<ul class="pagination pagination-lg justify-content-center">
			<li class="page-item">
				<a class="page-link" href="./index">1</a></li>
			<li class="page-item active" aria-current="page">
				<span class="page-link">
					2
					<span class="sr-only">(current)</span>
				</span>
			</li>

			<li class="page-item">
				<a class="page-link" href="<?php  echo BASE_URL; ?>">3</a></li>
		</ul>
	</nav>
</div>