<link rel="stylesheet" href="<?php  echo BASE_URL; ?>layout/admin/css/style.css"/>
<div id="container">
	<section id="contenido" >
				<article >
					<h1><img src="<?php echo $layout['img']; ?>jQuery_logo.png" width="120" alt="jQuery" title="jQuery">
						Implementaciones de "JQuery"
					</h1>
					<h2>¿Qué es jQuery?</h2>
					<p>Query es una biblioteca JavaScript liviana de "escribir menos, hacer más". El propósito de 
						jQuery es facilitar el uso de JavaScript en su sitio web. jQuery toma muchas tareas 
						comunes que requieren muchas líneas de código  JavaScript para llevarlas a cabo y las 
						envuelve en métodos que puede llamar con una sola línea de código. jQuery también 
						simplifica muchas de las cosas complicadas de JavaScript, como las llamadas AJAX y la 
						manipulación DOM.
					</p>
					<p>La biblioteca jQuery contiene las siguientes características:
						<ul>
							<li>Selección de elementos DOM.</li>
							<li>Interactividad y modificaciones del árbol DOM, incluyendo soporte para CSS 1-3 y 
								un plugin básico de XPath.</li>
							<li>Eventos.</li>
							<li>Manipulación de la hoja de estilos CSS.</li>
							<li>Efectos y animaciones.</li>
							<li>Animaciones personalizadas.</li>
							<li>AJAX.</li>
							<li>Soporta extensiones.</li>
							<li>Utilidades varias como obtener información del navegador, operar con objetos y 
								vectores, funciones para rutinas comunes, etc.</li>
							<li>Compatible con los navegadores Mozilla Firefox 2.0+, Internet Explorer 6+, Safari 
								3+, Opera 10.6+ y Google Chrome 8+</li>
						</ul>
					</p>
				</article>
		</section>
		
	<div class="clearfix visible-sm-block"></div>
		
		<div class="row">
			<div class="col-xs-12 col-sm-6 col-md-3">
				<h2 class="demoHeaders">Marcar Calendario</h2>
				<div id="datepicker"></div>
				<br>
			</div>
			
			<div class="clearfix visible-sm-block"></div>
			
			<div class="col-xs-12 col-sm-6 col-md-3">
				<br><br>
				<p>
					<label for="spinner">Spinner:</label>
					<input id="spinner" name="value">
				</p>
			</div>
			
			<div class="clearfix visible-sm-block"></div>

			<div class="col-xs-12 col-sm-6 col-md-3">
				<br><br>
				<p>
					<button id="disable">deshabilitar</button>
					<button id="destroy">Habilitar</button>
				</p>
			</div>
			
			<div class="clearfix visible-sm-block"></div>
			
			<div class="col-xs-12 col-sm-6 col-md-3" id="div1" style="height:100px;width:300px;border:1px solid 
				black;background-color:#ffaa00;">
				<h2>Que es jquery?</h2>
				<p>jQuery es una biblioteca JavaScript liviana de "escribir menos, hacer más"..</p>
				<p>El propósito de jQuery es facilitar el uso de JavaScript en su sitio web..</p>
			</div>

			<div class="clearfix visible-sm-block"></div>

			<div class="col-xs-12 col-sm-6 col-md-3">
				<br><br>
				<h2 class="demoHeaders">Progressbar</h2>
				<div id="progressbar"></div>

			</div>

			<div class="clearfix visible-sm-block"></div>

			<div class="col-xs-12 col-sm-6 col-md-3">
				<br><br>
				<h2 class="demoHeaders">Menú de Selección</h2>
				<select id="selectmenu">
					<option>Pequeño</option>
					<option selected="selected">Mediano</option>
					<option>Grande</option>
				</select>
			</div>

			<div class="clearfix visible-sm-block"></div>

			<div class="col-xs-12 col-sm-6 col-md-3">
				<br><br>
				<h2 class="demoHeaders">Menu</h2>
				<ul style="width:100px;" id="menu">
					<li><div>Producto 1</div></li>
					<li><div>Producto 2</div></li>
					<li><div>Producto 3</div>
						<ul>
							<li><div>Producto 3-1</div></li>
							<li><div>Producto 3-2</div></li>
							<li><div>Producto 3-3</div></li>
							<li><div>Producto 3-4</div></li>
							<li><div>Producto 3-5</div></li>
						</ul>
					</li>
				</ul>
				<br><br>
			</div>

			<div class="clearfix visible-sm-block"></div>

			<div class="col-xs-12 col-sm-6 col-md-3">
				<br><br>
				<h2 class="demoHeaders">Acordeón</h2>
				<div id="accordion">
					<h3>Opción 1</h3>
					<div>En esta parte se puede colocar información importante para el usuario.</div>
					<h3>Opción 2</h3>
					<div>como contenido de los elementos de Jquery.</div>
					<h3>Opción 3</h3>
					<div>y los posibles usos que se puden aplicar a nuestra página web.</div>
				</div>
			</div>
	</div>
</div>