<section class="content">
      	<div class="container-fluid">
      		<div class="card card-danger">
	            <div class="card-header">
	            	<h3 class="card-title">Consulta de Productos</h3>
	            </div>
	            
	            
              <!-- /.card-header -->
              	<div class="card-body">
               		<table id="consulta_producto" class="display" style="width: 100%">
		                <thead>
		                	<tr>
			                    <th>Id Producto</th>
			                    <th>Fecha</th>
			                    <th>Descripcion</th>
			                    <th>Id tipo producto</th>
			                    <th>Tipo producto</th>
			                    <th>Clasificación</th>
			                    <th>Destacado</th>
			                    <th>Fotografía</th>
			                    <th>Precio</th>
			                    <th>Iva</th>
			                    <th>Estado Registro</th>
		                  	</tr>
		                </thead>
                  
                  
                </table>
              </div>
              <!-- /.card-body -->
        	</div>
        	<button type="button" id="consultar" class="btn btn-danger">Consulta</button>
    	</div>
</section>