
<section class="content">
    <div class="card card-warning ">
        <div class="card-header">
          <h1 class="card-title">Mantenimiento de Productos</h1>
        </div>
        <div class="card-body" >
        	<table id="product"></table>
			<div id="menu_product"></div>
			<br>
        </div>
        <!-- /.card-body -->
    </div>
</section>




<div class="modal fade" id="Mod_foto" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Subir Foto</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
      	<form method="post" enctype="multipart/form-data">
        	<input id="input-b1" name="input-b1" type="file" class="file" data-browse-on-zone-click="true" data-msg-placeholder="Seleccione archivo para subir..."></input>
    	</form>
      </div>
      
    </div>
  </div>
</div>
