<style>

@media (min-width: 1200px)
.row:before, .row:after {
    display: table;
    line-height: 0;
    content: "";
    clear: both;
}

 .span3 li {
    line-height: 20px;
    align-content: center;
    text-align: center;
    
}
a {
    color: #08c;
    text-decoration: none;
}
.foto img {
    width: 300 px;
    height: 300 px;
    max-width: 100%;
    vertical-align: middle;
    border: 0;
    -ms-interpolation-mode: bicubic;
}
.thumbnails {
    margin-left: -20px;
    list-style: none;
    *zoom: 1;
}
.product-box{
	align-content: stretch;
}

.span3 ul{
    width: 120px;
    display: inline-tabla;
}

[class*="span"] {
    float: left;
    min-height: 1px;
    margin-left: 20px;
}
</style>


<section class="main-content content">
		<div class="contenedormenu info-box">	
			<div class="span3" id="detalle_productos">
				
			</div>
			<div class="clearfix visible-sm-block"></div>
		</div>
</section>