<section class="content">
	<div class="container-fluid">
		<div class="row">
			<div class="col-12" >
				<div class="card card-primary">
					<div class="card-header">
						<h3 class="card-title">Subir Imagen</h3>
					</div>
				</div>
				<form role="form" action="" method="post" enctype="multipart/form-data" id="">
				<div class="card-body">
					<div class="form-group">
						<label>Ingrese nombre del archivo</label>
						<input type="text" name="nomb_imagen" required class="form-control" placeholder="Nombre de foto">
					</div>
					<div class="form-group">
                    <label for="exampleInputFile">File input</label>
                    <div class="input-group">
                      <div class="custom-file">
                        <input type="file" class="custom-file-input" id="exampleInputFile">
                        <label class="custom-file-label" for="exampleInputFile">Elige un archivo</label>
                      </div>
                      <div class="input-group-append">
                        <span class="input-group-text" id="">Upload</span>
                      </div>
                    </div>
                  </div>
				</div>
					<div class="card-footer">
                  <button type="submit" class="btn btn-primary">Submit</button>
                </div>
				</form>
			</div>
		</div>
		
	</div>
</section>