<style type="text/css">
h3 {text-align: center;}
</style>

<section class="content">
    <div class="container-fluid">
    <div class="card card-info ">
	<br>
	<div align="center">
	<h3>Consulta de Solicitudes</h3>
	</div>
	<br>
	<button type="button" id="consultar" class="btn btn-info">Consulta</button>      
       	<div class="card-body">
      		<table id="consulta_solicitud" class="display" style="width: 100%">
	            <thead>
	              	<tr>
		                <th>Indice</th>
		                <th>Descripción</th>
		                <th>Teléfono</th>
		                <th>Dirección</th>
		                <th>Correo Electronico</th>
		                <th>Puesto</th>
		                <th>Fotografía</th>
		                <th>Curriculum</th>
		                <th>Estado Registro</th>
		           	</tr>
		        </thead>
            </table>
        </div>
        </div>
    </div>	
</section>