<style>
	.card-body {
				
				
				text-align: center;
				font-family: Poppins;
				font-size: 20px;
				color: #290673;
			}
</style>

<section class="content">
      	<div class="container-fluid">
      		<div class="card card-succes">
	            <div class="card-header">
      	<button type="button" id="consultar" class="btn btn-success btn-lg">Consulta de Solicitudes</button>
	            </div>
              <!-- /.card-header -->
              	<div class="card-body">
               		<table id="consulta_mar_grid" class="display" style="width: 100%" bgcolor=FFCECB>
		                <thead>
		                	<tr>
			                    <th>Id Solicitud</th>
			                    <th>Descripción</th>
			                    <th>Telefono</th>
			                    <th>Dirección</th>
			                    <th>Correo</th>
			                    <th>Puesto</th>
			                    <th>Fotografía</th>
			                    <th>Curriculum</th>
			                    <th>Estado Registro</th>
		                  	</tr>
		                </thead>
                  
                  
                </table>
              </div>
              <!-- /.card-body -->
        	</div>
        	
    	</div>
</section>