<section class="content">
    <div class="card card-warnig ">
        <div class="card-header">
        
		  <font color="Olive" face="Comic Sans MS,arial">        
	          <h1 class="card-title">Mantenimiento de Solicitudes con JqGrid</h1>
	          
			  <h1 align="center"> </h1>
				
		</font>
        </div>
        <div class="card-body" >
        	<table id="mar_grid"></table>
			<div id="men"></div>
			<br>
        </div>
    </div>
</section>