
		
		

				<style>
					table.dataTable thead {
						background: linear-gradient(to right, 	#84c6ed, #1a3747);
						color:white;
					}
					
					table{
				background: linear-gradient(to right, 	#00ffff, #1a3747 );
						
						
					}
					
			body{
				background: linear-gradient(to right, #0aff0a, #0055ff );

			}

			td{
				background: linear-gradient(to right, ##00007f, #00007f );
				color: white;
			}

			.myDiv {
				border: 5px outset linear-gradient(to right, #00aa00, #00007f );
				background: linear-gradient(to right, #0055ff, #0aff0a );
				text-align: center;
				font-family: Homer Simpson UI;
				font-size: 20px;
				color: white;
			}
				</style>

			 <body>
			  
		<div class="myDiv">
			<h1>DataTable</h1>


		</div>
			   
				
					<<div class="card-body">
						
			<table id="tablaUsuarios" class="display" style="width: 100%">
	            <thead>
	              	<tr>
		                <th>Id_solicitud</th>
						<th>Descripcion</th>
						<th>Teléfono</th>
						<th>Dirección</th>
						<th>Correo</th>
						<th>Empleo</th>
						<th>Fotografia</th>
						<th>Curriculum</th>
						<th>Estado</th>
		           	</tr>
		        </thead>
            </table>
					   </div>
				  
				
				 <!--Botones-->
				 <input type="button" class = "btn btn-info"  name="Mantenimiento" onclick="window.location.href='Jqgrid'" value="Regresar"><br><br>
				 <button type="button" id="consultar" class="btn btn-info">Consulta</button> 
				
				</body>
				