<style>


			body{
				background: linear-gradient(to right, #0aff0a, #0055ff );
				
			}

			td{
				background: linear-gradient(to right, ##00007f, #00007f );
			color:#167699;
			}

			.myDiv {
				border: 5px outset linear-gradient(to right, #00aa00, #00007f );
				background: linear-gradient(to right, #0055ff, #0aff0a );
				text-align: center;
				font-family:Homer Simpson UI;
				font-size: 20px;
				color:white;
			}



		</style>
		



		<!--Tabla de Mantinimiento-->
		<p>&nbsp;</p>
		<p>&nbsp;</p>
		<div class="myDiv">
			<h1>JQGrid     </h1>


		</div>

		<p>&nbsp;</p>
		<p>&nbsp;</p>

		<div id="Tabla"align="center"  >
			<table id="crud" >
				<tr>
					<td>&nbsp;</td>
				</tr>
			</table>

			<div id="pcrud"></div>
		</div>



