 <section  class="homepage-slider" id="home-slider">
	<div class="flexslider">
		<ul class="slides">
			<li>
				<img src="<?php echo $layout['ruta_fotos']; ?>carousel/banner-1.jpeg" alt="" />
			</li>
			<li>
				<img src="<?php echo $layout['ruta_fotos']; ?>carousel/banner-2.jpeg" alt="" />
				<div class="intro">
					<h1>Mitad de temporada</h1>
					<p>
						<span>50% menos</span></p>
					<p>
						<span>En artículos seleccionados en línea y en tiendas</span></p>
				</div>
			</li>
		</ul>
	</div>
</section>
<section class="header_text">
	Ahora puedes comprar desde casa y te entregaremos directamente a tu puerta.
	<br/>Todos los meses traemos nueva mercaderia a los mejores precios.
</section>
<section class="main-content">
	<div class="row">
		<div class="span12">
			<div class="row">
				<div class="span12">
					<h4 class="title">
						<span class="pull-left">
							<span class="text">
								<span class="line">PRODUCTOS
									<strong>DESTACADOS</strong></span></span></span>
						<span class="pull-right">
							<a class="left button" href="#myCarousel" data-slide="prev"></a>
							<a class="right button" href="#myCarousel" data-slide="next"></a>
						</span>
					</h4>
					<div id="myCarousel" class="myCarousel carousel slide">
						<div class="carousel-inner">
							<div class="active item">
								<ul class="thumbnails">
									<li class="span3">
										<div class="product-box">
											<span class="sale_tag"></span>
											<a href="product_detail.html"><img alt="" src="<?php echo $layout['ruta_fotos']; ?>ladies/1.jpg"></a><br/>
											<a href="product_detail.html" class="title">Vestido Casual</a><br/>
											<a href="#" class="category">Estampado</a>
											<p class="price">$341</p>
										</div>
									</li>
									<li class="span3">
										<div class="product-box">
											<a href="product_detail.html"><img alt="" src="<?php echo $layout['ruta_fotos']; ?>ladies/2.jpg"></a><br/>
											<a href="product_detail.html" class="title">Vestido casual</a><br/>
											<a href="#" class="category">Estampado de Flores</a>
											<p class="price">$28</p>
										</div>
									</li>
									<li class="span3">
										<div class="product-box">
											<span class="sale_tag"></span>
											<a href="product_detail.html"><img alt="" src="<?php echo $layout['ruta_fotos']; ?>ladies/3.jpg""></a><br/>
											<a href="product_detail.html" class="title">Vestido casual</a><br/>
											<a href="#" class="category">Negro de Algodón</a>
											<p class="price">$341</p>
										</div>
									</li>
									<li class="span3">
										<div class="product-box">
											<span class="sale_tag"></span>
											<a href="product_detail.html"><img alt="" src="themes/images/ladies/4.jpg""></a><br/>
											<a href="product_detail.html" class="title">Blusa de algón</a><br/>
											<a href="#" class="category">Color Gris</a>
											<p class="price">$49</p>
										</div>
									</li>
								</ul>
							</div>
							<div class="item">
								<ul class="thumbnails">
									<li class="span3">
										<div class="product-box">
											<a href="product_detail.html"><img alt="" src="themes/images/ladies/5.jpg""></a><br/>
											<a href="product_detail.html" class="title">Vestido casual</a><br/>
											<a href="#" class="category">Negro de Lana</a>
											<p class="price">$35</p>
										</div>
									</li>
									<li class="span3">
										<div class="product-box">
											<a href="product_detail.html"><img alt="" src="themes/images/ladies/6.jpg""></a><br/>
											<a href="product_detail.html" class="title">Bulsa Larga</a><br/>
											<a href="#" class="category">De Seda</a>
											<p class="price">$61</p>
										</div>
									</li>
									<li class="span3">
										<div class="product-box">
											<a href="product_detail.html"><img alt="" src="themes/images/ladies/7.jpg""></a><br/>
											<a href="product_detail.html" class="title">Vestido casual</a><br/>
											<a href="#" class="category">Rayada con falda verde</a>
											<p class="price">$233</p>
										</div>
									</li>
									<li class="span3">
										<div class="product-box">
											<a href="product_detail.html"><img alt="" src="themes/images/ladies/8.jpg""></a><br/>
											<a href="product_detail.html" class="title">Blusa larga</a><br/>
											<a href="#" class="category">De lana rayada</a>
											<p class="price">$134</p>
										</div>
									</li>
								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>
			<br/>
			<div class="row">
				<div class="span12">
					<h4 class="title">
						<span class="pull-left">
							<span class="text">
								<span class="line">Productos de
									<strong>Hombre</strong></span></span></span>
						<span class="pull-right">
							<a class="left button" href="#myCarousel-2" data-slide="prev"></a>
							<a class="right button" href="#myCarousel-2" data-slide="next"></a>
						</span>
					</h4>
					<div id="myCarousel-2" class="myCarousel carousel slide">
						<div class="carousel-inner">
							<div class="active item">
								<ul class="thumbnails">
									<li class="span3">
										<div class="product-box">
											<span class="sale_tag"></span>
											<a href="product_detail.html"><img alt="" src="themes/images/Men/img1.png"></a><br/>
											<a href="product_detail.html" class="title">Traje de algodón</a><br/>
											<a href="#" class="category">Color Negro</a>
											<p class="price">$341</p>
										</div>
									</li>
									<li class="span3">
										<div class="product-box">
											<a href="product_detail.html"><img alt="" src="themes/images/Men/img2.png"></a><br/>
											<a href="product_detail.html" class="title">Camisa de algodon</a><br/>
											<a href="#" class="category">Estampada</a>
											<p class="price">$28</p>
										</div>
									</li>
									<li class="span3">
										<div class="product-box">
											<span class="sale_tag"></span>
											<a href="product_detail.html"><img alt="" src="themes/images/Men/img3.png"></a><br/>
											<a href="product_detail.html" class="title">Traje de Cachemir</a><br/>
											<a href="#" class="category">Blanco Cuadriculado</a>
											<p class="price">$341</p>
										</div>
									</li>
									<li class="span3">
										<div class="product-box">
											<span class="sale_tag"></span>
											<a href="product_detail.html"><img alt="" src="themes/images/Men/img4.png"></a><br/>
											<a href="product_detail.html" class="title">shorts de algodon</a><br/>
											<a href="#" class="category">Negro cuadriculadot</a>
											<p class="price">$49</p>
										</div>
									</li>
								</ul>
							</div>
							<div class="item">
								<ul class="thumbnails">
									<li class="span3">
										<div class="product-box">
											<a href="product_detail.html"><img alt="" src="themes/images/Men/img5.png"></a><br/>
											<a href="product_detail.html" class="title">Camisa de gabardina</a><br/>
											<a href="#" class="category">Rojo Cuadriculado</a>
											<p class="price">$35</p>
										</div>
									</li>
									<li class="span3">
										<div class="product-box">
											<a href="product_detail.html"><img alt="" src="themes/images/Men/img6.png"></a><br/>
											<a href="product_detail.html" class="title">Ropa interior térmica</a><br/>
											<a href="#" class="category">Color Verde Musgo</a>
											<p class="price">$61</p>
										</div>
									</li>
									<li class="span3">
										<div class="product-box">
											<a href="product_detail.html"><img alt="" src="themes/images/Men/img7.png"></a><br/>
											<a href="product_detail.html" class="title">Traje de estambre</a><br/>
											<a href="#" class="category">Gris Rayado</a>
											<p class="price">$233</p>
										</div>
									</li>
									<li class="span3">
										<div class="product-box">
											<a href="product_detail.html"><img alt="" src="themes/images/Men/img8.png"></a><br/>
											<a href="product_detail.html" class="title">Traje de seda</a><br/>
											<a href="#" class="category">Color Corinto</a>
											<p class="price">$134</p>
										</div>
									</li>
								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>

		</div>
	</div>
</section>
<section class="our_client">
	<h4 class="title">
		<span class="text">Proveedores</span></h4>
	<div class="row">
		<div class="span2">
			<a href="#"><img alt="" src="<?php echo $layout['ruta_fotos']; ?>clients/14.png"></a>
		</div>
		<div class="span2">
			<a href="#"><img alt="" src="<?php echo $layout['ruta_fotos']; ?>clients/35.png"></a>
		</div>
		<div class="span2">
			<a href="#"><img alt="" src="<?php echo $layout['ruta_fotos']; ?>clients/1.png"></a>
		</div>
		<div class="span2">
			<a href="#"><img alt="" src="<?php echo $layout['ruta_fotos']; ?>clients/2.png"></a>
		</div>
		<div class="span2">
			<a href="#"><img alt="" src="<?php echo $layout['ruta_fotos']; ?>clients/3.png"></a>
		</div>
		<div class="span2">
			<a href="#"><img alt="" src="<?php echo $layout['ruta_fotos']; ?>clients/4.png"></a>
		</div>
	</div>
</section>