<div class="card card-info">
	<div class="card-header">
		<h3 class="card-title">Modificar Usuarios</h3>
	</div>
	<!-- /.card-header -->
	<!-- form start -->
	<form id="frmUsuario" class="form-horizontal" method="post">
		<div class="card-body">
		<div class="form-group row">
				<label for="id_usuario" class="col-sm-2 col-form-label">Id Usuario</label>
				<div class="col-sm-10">
					<input type="text" class="form-control" id="id_usuario" name="id_usuario" placeholder="Id Usuario">
				</div>
			</div>
			<div class="form-group row">
				<label for="descripcion" class="col-sm-2 col-form-label">Descripcion</label>
				<div class="col-sm-10">
					<input type="text" class="form-control" id="descripcion" name="descripcion" placeholder="Descripcion">
				</div>
			</div>
			<div class="form-group row">
				<label for="usuario" class="col-sm-2 col-form-label">Usuario</label>
				<div class="col-sm-10">
					<input type="text" class="form-control" id="usuario" name="usuario" placeholder="Usuario">
				</div>
			</div>
			<div class="form-group row">
				<label for="usuario" class="col-sm-2 col-form-label">Password</label>
				<div class="col-sm-10">
					<input type="password" class="form-control" id="clave" name="clave" placeholder="Clave de Acceso">
				</div>
			</div>			
		</div>
		<!-- /.card-body -->
		<div class="card-footer">
			<button type="button" id="aceptar" class="btn btn-info">Grabar</button>
			<button type="reset" class="btn btn-default">Cancel</button>
		</div>
		<!-- /.card-footer -->
	</form>
</div>