<section class="content">
      	<div class="container-fluid">
      		<div class="card card-success">
      			<div class="card-header">
      				<h3 class="card-title">Consulta de Departamento</h3>
      			</div>
              <!-- /.card-header -->
              	<div class="card-body">
              		<table id="consulta_depto" class="display" style="width: 100%">
              			<thead>
			                <tr>
			                	<th>ID Departamento</th>
			                    <th>Descripción</th>
			                    <th>Estado</th>
			                </tr>
		                </thead>
                  
	                  	
                	</table>
              	</div>
              
        	</div>
        	
        	<button type="button" id="consultar" class="btn btn-success">Consulta</button>
    	</div>
</section>