<div class="card card-danger">
	<div class="card-header">
		<h3 class="card-title">Eliminar Departamentos</h3>
	</div>
	<!-- /.card-header -->
	<!-- form start -->
	<form id="frmDepartamento" class="form-horizontal" method="post">
		<div class="card-body">
		<div class="form-group row">
				<label for="id_departamento" class="col-sm-2 col-form-label">Id Departamento</label>
				<div class="col-sm-10">
					<input type="text" class="form-control" id="id_departamento" name="id_departamento" placeholder="Id Departamento">
				</div>
			</div>
			<div class="form-group row">
				<label for="descripcion" class="col-sm-2 col-form-label">Descripcion</label>
				<div class="col-sm-10">
					<input type="text" class="form-control" id="descripcion" name="descripcion" placeholder="Descripcion">
				</div>
			</div>
			
			<div class="form-group row">
				<label for="estado_registro" class="col-sm-2 col-form-label">Estado Registro</label>
				<div class="col-sm-10">
					<input  class="form-control" id="estado_registro" name="estado_registro" placeholder="Estado del Registro">
				</div>
			</div>			
		</div>
		<!-- /.card-body -->
		<div class="card-footer">
			<button type="button" id="aceptar" class="btn btn-danger">Eliminar</button>
			<button type="reset" class="btn btn-default">Cancel</button>
		</div>
		<!-- /.card-footer -->
	</form>
</div>